import fs from 'fs';
import path from 'path';
import type {
  Medicine,
  MedicineBatch,
  InventoryMovement,
  Sale,
  CustomerReturn,
  Supplier,
  Purchase,
  Customer,
  Expense,
  AuditLog,
  PharmacySettings,
} from '../src/types';

export interface ServerDatabase {
  medicines: Medicine[];
  medicine_batches: MedicineBatch[];
  inventory_movements: InventoryMovement[];
  sales: Sale[];
  processed_idempotency_keys: Record<string, string>; // idempotency_key -> sale_id
  customer_returns: CustomerReturn[];
  suppliers: Supplier[];
  purchases: Purchase[];
  customers: Customer[];
  expenses: Expense[];
  audit_logs: AuditLog[];
  settings: PharmacySettings;
}

const DATA_DIR = path.resolve('data');
const DB_FILE = path.join(DATA_DIR, 'server-db.json');

const INITIAL_SERVER_SETTINGS: PharmacySettings = {
  pharmacy_name: 'GIGA CHEMIST',
  tagline: 'Healthcare & Pharmaceutical Dispensing Centre',
  address: 'Commercial Street, Kitale, Kenya',
  phone: '+254 700 123 456',
  email: 'orders@gigachemist.co.ke',
  currency: 'KES',
  tax_rate: 0,
  tax_enabled: false,
  receipt_header: 'GIGA CHEMIST\nKitale, Kenya\nOfficial Dispensing Receipt',
  receipt_footer: 'Thank you for choosing GIGA CHEMIST!\nMedicines dispensed correctly cannot be returned.\nGet well soon.',
  printer_type: '80mm',
  auto_print_receipt: true,
  low_stock_threshold: 20,
  expiry_warning_days: 90,
  require_prescription_warning: true,
  allow_walk_in: true,
  version: '1.0.0-pwa',
  updated_at: new Date().toISOString(),
};

function getSeedData(): ServerDatabase {
  const todayStr = new Date().toISOString().split('T')[0];
  const datePlusDays = (days: number) => {
    const d = new Date();
    d.setDate(d.getDate() + days);
    return d.toISOString().split('T')[0];
  };

  const medicines: Medicine[] = [
    {
      id: 'med-001',
      name: 'Paracetamol 500mg',
      generic_name: 'Paracetamol (Acetaminophen)',
      brand_name: 'Panadol',
      sku: 'MED-PCM-500',
      barcode: '616400010012',
      category: 'Analgesics & Antipyretics',
      medicine_type: 'Pain Relief & Fever',
      dosage_strength: '500mg',
      dosage_form: 'Tablet',
      manufacturer: 'GlaxoSmithKline',
      description: 'Effective relief from headache, fever, muscle aches, and pain.',
      purchase_price: 3.5,
      selling_price: 10.0,
      wholesale_price: 8.0,
      min_selling_price: 7.0,
      current_stock: 350,
      reorder_level: 50,
      unit: 'Strips (10 tabs)',
      prescription_required: false,
      status: 'active',
      created_at: todayStr,
      updated_at: todayStr,
      created_by: 'Admin',
      updated_by: 'Admin',
      version: 1,
    },
    {
      id: 'med-002',
      name: 'Amoxicillin 500mg Capsules',
      generic_name: 'Amoxicillin Trihydrate',
      brand_name: 'Amoxil',
      sku: 'MED-AMX-500',
      barcode: '616400010029',
      category: 'Antibiotics',
      medicine_type: 'Penicillin Antibiotic',
      dosage_strength: '500mg',
      dosage_form: 'Capsule',
      manufacturer: 'Cosmos Limited',
      description: 'Broad-spectrum antibiotic for bacterial infections. Prescription mandatory.',
      purchase_price: 7.0,
      selling_price: 15.0,
      wholesale_price: 12.0,
      min_selling_price: 10.0,
      current_stock: 180,
      reorder_level: 40,
      unit: 'Strips (10 caps)',
      prescription_required: true,
      status: 'active',
      created_at: todayStr,
      updated_at: todayStr,
      created_by: 'Admin',
      updated_by: 'Admin',
      version: 1,
    },
    {
      id: 'med-003',
      name: 'Cetirizine 10mg Tablets',
      generic_name: 'Cetirizine Hydrochloride',
      brand_name: 'Zyrtec',
      sku: 'MED-CTZ-010',
      barcode: '616400010036',
      category: 'Antihistamines',
      medicine_type: 'Allergy Relief',
      dosage_strength: '10mg',
      dosage_form: 'Tablet',
      manufacturer: 'Harleys Pharmaceuticals Ltd',
      description: 'Second-generation antihistamine for seasonal allergic rhinitis and hives.',
      purchase_price: 5.0,
      selling_price: 15.0,
      wholesale_price: 11.0,
      min_selling_price: 10.0,
      current_stock: 120,
      reorder_level: 30,
      unit: 'Strips (10 tabs)',
      prescription_required: false,
      status: 'active',
      created_at: todayStr,
      updated_at: todayStr,
      created_by: 'Admin',
      updated_by: 'Admin',
      version: 1,
    },
    {
      id: 'med-004',
      name: 'Metformin 500mg Tablets',
      generic_name: 'Metformin Hydrochloride',
      brand_name: 'Glucophage',
      sku: 'MED-MET-500',
      barcode: '616400010043',
      category: 'Antidiabetics',
      medicine_type: 'Type 2 Diabetes',
      dosage_strength: '500mg',
      dosage_form: 'Tablet',
      manufacturer: 'Merck Healthcare',
      description: 'First-line medication for the treatment of type 2 diabetes.',
      purchase_price: 8.0,
      selling_price: 20.0,
      wholesale_price: 15.0,
      min_selling_price: 14.0,
      current_stock: 150,
      reorder_level: 30,
      unit: 'Strips (14 tabs)',
      prescription_required: true,
      status: 'active',
      created_at: todayStr,
      updated_at: todayStr,
      created_by: 'Admin',
      updated_by: 'Admin',
      version: 1,
    },
    {
      id: 'med-005',
      name: 'Omeprazole 20mg Capsules',
      generic_name: 'Omeprazole Delayed-Release',
      brand_name: 'Losec',
      sku: 'MED-OMP-020',
      barcode: '616400010050',
      category: 'Gastrointestinal',
      medicine_type: 'Proton Pump Inhibitor (PPI)',
      dosage_strength: '20mg',
      dosage_form: 'Capsule',
      manufacturer: 'AstraZeneca',
      description: 'Suppresses stomach acid secretion; for acid reflux and GERD.',
      purchase_price: 10.0,
      selling_price: 25.0,
      wholesale_price: 18.0,
      min_selling_price: 18.0,
      current_stock: 80,
      reorder_level: 25,
      unit: 'Strips (14 caps)',
      prescription_required: false,
      status: 'active',
      created_at: todayStr,
      updated_at: todayStr,
      created_by: 'Admin',
      updated_by: 'Admin',
      version: 1,
    },
    {
      id: 'med-006',
      name: 'Azithromycin 500mg Tablets',
      generic_name: 'Azithromycin Monohydrate',
      brand_name: 'Zithromax',
      sku: 'MED-AZM-500',
      barcode: '616400010067',
      category: 'Antibiotics',
      medicine_type: 'Macrolide Antibiotic',
      dosage_strength: '500mg',
      dosage_form: 'Tablet',
      manufacturer: 'Pfizer',
      description: 'Used for respiratory, skin, and ear bacterial infections.',
      purchase_price: 180.0,
      selling_price: 350.0,
      wholesale_price: 280.0,
      min_selling_price: 260.0,
      current_stock: 45,
      reorder_level: 15,
      unit: 'Pack (3 tabs)',
      prescription_required: true,
      status: 'active',
      created_at: todayStr,
      updated_at: todayStr,
      created_by: 'Admin',
      updated_by: 'Admin',
      version: 1,
    },
    {
      id: 'med-007',
      name: 'Salbutamol 100mcg Inhaler',
      generic_name: 'Salbutamol Sulfate',
      brand_name: 'Ventolin',
      sku: 'MED-SLB-100',
      barcode: '616400010074',
      category: 'Respiratory',
      medicine_type: 'Bronchodilator',
      dosage_strength: '100mcg/dose',
      dosage_form: 'Inhaler',
      manufacturer: 'GlaxoSmithKline',
      description: 'Fast-acting relief inhaler for asthma and wheezing.',
      purchase_price: 220.0,
      selling_price: 450.0,
      wholesale_price: 380.0,
      min_selling_price: 350.0,
      current_stock: 22,
      reorder_level: 10,
      unit: 'Inhaler (200 doses)',
      prescription_required: true,
      status: 'active',
      created_at: todayStr,
      updated_at: todayStr,
      created_by: 'Admin',
      updated_by: 'Admin',
      version: 1,
    },
    {
      id: 'med-008',
      name: 'Ibuprofen 400mg Tablets',
      generic_name: 'Ibuprofen',
      brand_name: 'Brufen',
      sku: 'MED-IBU-400',
      barcode: '616400010081',
      category: 'Analgesics & Antipyretics',
      medicine_type: 'NSAID Anti-inflammatory',
      dosage_strength: '400mg',
      dosage_form: 'Tablet',
      manufacturer: 'Laboratory & Allied Ltd',
      description: 'Nonsteroidal anti-inflammatory for joint pain, dental pain, and inflammation.',
      purchase_price: 4.0,
      selling_price: 12.0,
      wholesale_price: 8.5,
      min_selling_price: 8.0,
      current_stock: 12,
      reorder_level: 30,
      unit: 'Strips (10 tabs)',
      prescription_required: false,
      status: 'active',
      created_at: todayStr,
      updated_at: todayStr,
      created_by: 'Admin',
      updated_by: 'Admin',
      version: 1,
    },
  ];

  const medicine_batches: MedicineBatch[] = [
    {
      id: 'bat-001',
      medicine_id: 'med-001',
      medicine_name: 'Paracetamol 500mg',
      batch_number: 'PCM-2601-A',
      supplier_id: 'sup-001',
      supplier_name: 'Harleys Pharmaceuticals Ltd',
      quantity_received: 200,
      quantity_available: 150,
      purchase_price: 3.5,
      manufacturing_date: '2025-06-01',
      expiry_date: datePlusDays(180),
      received_date: '2025-07-10',
      purchase_invoice: 'INV-HRL-8901',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
    {
      id: 'bat-002',
      medicine_id: 'med-001',
      medicine_name: 'Paracetamol 500mg',
      batch_number: 'PCM-2602-B',
      supplier_id: 'sup-001',
      supplier_name: 'Harleys Pharmaceuticals Ltd',
      quantity_received: 200,
      quantity_available: 200,
      purchase_price: 3.5,
      manufacturing_date: '2026-01-15',
      expiry_date: datePlusDays(540),
      received_date: '2026-02-01',
      purchase_invoice: 'INV-HRL-9420',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
    {
      id: 'bat-003',
      medicine_id: 'med-002',
      medicine_name: 'Amoxicillin 500mg Capsules',
      batch_number: 'AMX-2509-EXP',
      supplier_id: 'sup-002',
      supplier_name: 'Cosmos Limited',
      quantity_received: 50,
      quantity_available: 30,
      purchase_price: 7.0,
      manufacturing_date: '2024-04-01',
      expiry_date: datePlusDays(22),
      received_date: '2024-05-10',
      purchase_invoice: 'INV-CSM-4412',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
    {
      id: 'bat-004',
      medicine_id: 'med-002',
      medicine_name: 'Amoxicillin 500mg Capsules',
      batch_number: 'AMX-2601-FRESH',
      supplier_id: 'sup-002',
      supplier_name: 'Cosmos Limited',
      quantity_received: 150,
      quantity_available: 150,
      purchase_price: 7.0,
      manufacturing_date: '2026-01-05',
      expiry_date: datePlusDays(700),
      received_date: '2026-02-15',
      purchase_invoice: 'INV-CSM-4980',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
    {
      id: 'bat-005',
      medicine_id: 'med-003',
      medicine_name: 'Cetirizine 10mg Tablets',
      batch_number: 'CTZ-2603',
      supplier_id: 'sup-001',
      supplier_name: 'Harleys Pharmaceuticals Ltd',
      quantity_received: 120,
      quantity_available: 120,
      purchase_price: 5.0,
      manufacturing_date: '2025-10-01',
      expiry_date: datePlusDays(450),
      received_date: '2025-11-20',
      purchase_invoice: 'INV-HRL-9800',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
    {
      id: 'bat-006',
      medicine_id: 'med-004',
      medicine_name: 'Metformin 500mg Tablets',
      batch_number: 'MET-2604',
      supplier_id: 'sup-003',
      supplier_name: 'Laboratory & Allied Ltd',
      quantity_received: 150,
      quantity_available: 150,
      purchase_price: 8.0,
      manufacturing_date: '2025-11-01',
      expiry_date: datePlusDays(600),
      received_date: '2025-12-05',
      purchase_invoice: 'INV-LBA-3101',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
    {
      id: 'bat-007',
      medicine_id: 'med-005',
      medicine_name: 'Omeprazole 20mg Capsules',
      batch_number: 'OMP-2605',
      supplier_id: 'sup-002',
      supplier_name: 'Cosmos Limited',
      quantity_received: 80,
      quantity_available: 80,
      purchase_price: 10.0,
      manufacturing_date: '2025-08-01',
      expiry_date: datePlusDays(380),
      received_date: '2025-09-12',
      purchase_invoice: 'INV-CSM-5120',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
    {
      id: 'bat-008',
      medicine_id: 'med-006',
      medicine_name: 'Azithromycin 500mg Tablets',
      batch_number: 'AZM-2606',
      supplier_id: 'sup-001',
      supplier_name: 'Harleys Pharmaceuticals Ltd',
      quantity_received: 45,
      quantity_available: 45,
      purchase_price: 180.0,
      manufacturing_date: '2025-12-01',
      expiry_date: datePlusDays(480),
      received_date: '2026-01-10',
      purchase_invoice: 'INV-HRL-1045',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
    {
      id: 'bat-009',
      medicine_id: 'med-007',
      medicine_name: 'Salbutamol 100mcg Inhaler',
      batch_number: 'SLB-2607',
      supplier_id: 'sup-001',
      supplier_name: 'Harleys Pharmaceuticals Ltd',
      quantity_received: 22,
      quantity_available: 22,
      purchase_price: 220.0,
      manufacturing_date: '2025-09-01',
      expiry_date: datePlusDays(400),
      received_date: '2025-10-14',
      purchase_invoice: 'INV-HRL-1090',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
    {
      id: 'bat-010',
      medicine_id: 'med-008',
      medicine_name: 'Ibuprofen 400mg Tablets',
      batch_number: 'IBU-2508',
      supplier_id: 'sup-003',
      supplier_name: 'Laboratory & Allied Ltd',
      quantity_received: 100,
      quantity_available: 12,
      purchase_price: 4.0,
      manufacturing_date: '2025-01-10',
      expiry_date: datePlusDays(240),
      received_date: '2025-02-15',
      purchase_invoice: 'INV-LBA-2990',
      created_by: 'Admin',
      created_at: todayStr,
      status: 'active',
    },
  ];

  const suppliers: Supplier[] = [
    {
      id: 'sup-001',
      name: 'Harleys Pharmaceuticals Ltd',
      contact_person: 'David Kamau',
      phone: '+254 722 100 200',
      email: 'orders@harleys.co.ke',
      address: 'Industrial Area, Commercial Street, Nairobi',
      tax_pin: 'P051234567A',
      balance: 0,
      status: 'active',
      created_at: todayStr,
    },
    {
      id: 'sup-002',
      name: 'Cosmos Limited',
      contact_person: 'Sarah Njoroge',
      phone: '+254 733 300 400',
      email: 'sales@cosmos-pharm.com',
      address: 'Rangwe Road, Off Lunga Lunga, Nairobi',
      tax_pin: 'P051987654B',
      balance: 0,
      status: 'active',
      created_at: todayStr,
    },
    {
      id: 'sup-003',
      name: 'Laboratory & Allied Ltd',
      contact_person: 'Michael Ochieng',
      phone: '+254 711 500 600',
      email: 'supply@laballied.com',
      address: 'Mombasa Road, Nairobi',
      tax_pin: 'P051654321C',
      balance: 0,
      status: 'active',
      created_at: todayStr,
    },
  ];

  return {
    medicines,
    medicine_batches,
    inventory_movements: [],
    sales: [],
    processed_idempotency_keys: {},
    customer_returns: [],
    suppliers,
    purchases: [],
    customers: [
      {
        id: 'cus-001',
        name: 'Walk-in Customer',
        phone: '0700000000',
        email: '',
        address: 'Kitale Town',
        credit_balance: 0,
        total_spent: 0,
        created_at: todayStr,
      },
    ],
    expenses: [],
    audit_logs: [
      {
        id: 'aud-srv-001',
        user_id: 'system',
        user_name: 'Server Initializer',
        role: 'ADMIN',
        action: 'SERVER_BOOTSTRAP',
        entity: 'database',
        entity_id: 'server_db',
        new_value: 'Initialized relational database state',
        device_id: 'SERVER-MAIN',
        timestamp: Date.now(),
        date: todayStr,
      },
    ],
    settings: INITIAL_SERVER_SETTINGS,
  };
}

class ServerStore {
  private data: ServerDatabase;

  constructor() {
    if (!fs.existsSync(DATA_DIR)) {
      fs.mkdirSync(DATA_DIR, { recursive: true });
    }

    if (fs.existsSync(DB_FILE)) {
      try {
        const raw = fs.readFileSync(DB_FILE, 'utf-8');
        this.data = JSON.parse(raw);
      } catch (e) {
        console.error('Failed to parse existing server-db.json. Re-seeding...', e);
        this.data = getSeedData();
        this.persist();
      }
    } else {
      this.data = getSeedData();
      this.persist();
    }
  }

  public get(): ServerDatabase {
    return this.data;
  }

  public persist(): void {
    try {
      fs.writeFileSync(DB_FILE, JSON.stringify(this.data, null, 2), 'utf-8');
    } catch (e) {
      console.error('Failed to write server-db.json:', e);
    }
  }

  public reset(seed = true): void {
    this.data = seed ? getSeedData() : {
      medicines: [],
      medicine_batches: [],
      inventory_movements: [],
      sales: [],
      processed_idempotency_keys: {},
      customer_returns: [],
      suppliers: [],
      purchases: [],
      customers: [],
      expenses: [],
      audit_logs: [],
      settings: INITIAL_SERVER_SETTINGS,
    };
    this.persist();
  }
}

export const serverDb = new ServerStore();
