// GENERATED by scripts/build-online-api.mjs from server/online/vercel-entry.ts — do not edit. Run: npm run build:api

// server/online/vercel-entry.ts
import express3 from "express";

// server/online/app.ts
import fs from "fs";
import path from "path";
import express2 from "express";
import pg2 from "pg";

// server/http/common.ts
import express from "express";
function applyCommonMiddleware(app2) {
  const allowedOrigins = (process.env.ALLOWED_ORIGINS || "").split(",").map((o) => o.trim().replace(/\/$/, "")).filter(Boolean);
  app2.disable("x-powered-by");
  app2.use(express.json({ limit: "10mb" }));
  app2.use(express.urlencoded({ extended: true }));
  app2.use((req, res, next) => {
    const origin = req.headers.origin;
    if (origin && allowedOrigins.includes(origin)) {
      res.setHeader("Access-Control-Allow-Origin", origin);
      res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, PATCH, DELETE, OPTIONS");
      res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Device-Id");
    }
    if (origin) res.setHeader("Vary", "Origin");
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("Referrer-Policy", "same-origin");
    if (req.method === "OPTIONS") return res.sendStatus(204);
    next();
  });
}
function apiErrorHandler(err, req, res, next) {
  if (res.headersSent) return next(err);
  const status = typeof err?.status === "number" && err.status >= 400 && err.status < 600 ? err.status : 500;
  if (status >= 500) console.error("[API] Unhandled error:", err?.message || err);
  res.status(status).json({
    error: err?.type === "entity.parse.failed" ? "Request body is not valid JSON." : status >= 500 ? "Internal server error." : err?.message || "Bad request."
  });
}

// server/auth.ts
import crypto from "crypto";
var TOKEN_EXPIRY_SECONDS = 12 * 60 * 60;
var MIN_JWT_SECRET_LENGTH = 32;
function getJwtSecret() {
  const secret = process.env.JWT_SECRET?.trim();
  if (!secret || secret.length < MIN_JWT_SECRET_LENGTH) {
    throw new Error(
      `JWT_SECRET is missing or shorter than ${MIN_JWT_SECRET_LENGTH} characters. Set a long random JWT_SECRET in .env before starting the GIGA CHEMIST server.`
    );
  }
  return secret;
}
function signJwt(encodedHeader, encodedPayload) {
  return crypto.createHmac("sha256", getJwtSecret()).update(`${encodedHeader}.${encodedPayload}`).digest("base64").replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}
function hashCredential(secret, customSalt) {
  const salt = customSalt || crypto.randomBytes(16).toString("hex");
  const hash = crypto.pbkdf2Sync(secret, salt, 1e5, 64, "sha512").toString("hex");
  return { hash, salt, combined: `${salt}$${hash}` };
}
function verifyCredential(secret, storedHash, salt) {
  if (!secret || !storedHash) return false;
  if (storedHash.includes("$")) {
    const parts = storedHash.split("$");
    const actualSalt = parts.length >= 3 ? parts[parts.length - 2] : parts[0];
    const actualHash = parts[parts.length - 1];
    const { hash: hash2 } = hashCredential(secret, actualSalt);
    try {
      return crypto.timingSafeEqual(Buffer.from(hash2, "hex"), Buffer.from(actualHash, "hex"));
    } catch (e) {
      return false;
    }
  }
  if (!salt) return false;
  const { hash } = hashCredential(secret, salt);
  try {
    return crypto.timingSafeEqual(Buffer.from(hash, "hex"), Buffer.from(storedHash, "hex"));
  } catch (e) {
    return false;
  }
}
function base64UrlEncode(str) {
  return Buffer.from(str).toString("base64").replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}
function base64UrlDecode(str) {
  let base64 = str.replace(/-/g, "+").replace(/_/g, "/");
  while (base64.length % 4) {
    base64 += "=";
  }
  return Buffer.from(base64, "base64").toString("utf-8");
}
function createJwtToken(payload) {
  const now = Math.floor(Date.now() / 1e3);
  const fullPayload = {
    ...payload,
    iat: now,
    exp: now + TOKEN_EXPIRY_SECONDS
  };
  const header = { alg: "HS256", typ: "JWT" };
  const encodedHeader = base64UrlEncode(JSON.stringify(header));
  const encodedPayload = base64UrlEncode(JSON.stringify(fullPayload));
  return `${encodedHeader}.${encodedPayload}.${signJwt(encodedHeader, encodedPayload)}`;
}
function verifyJwtToken(token) {
  if (!token || typeof token !== "string") {
    return { valid: false, error: "Token missing or invalid format" };
  }
  const parts = token.split(".");
  if (parts.length !== 3) {
    return { valid: false, error: "Malformed JWT token structure" };
  }
  const [encodedHeader, encodedPayload, signature] = parts;
  const expected = Buffer.from(signJwt(encodedHeader, encodedPayload));
  const actual = Buffer.from(signature);
  if (actual.length !== expected.length || !crypto.timingSafeEqual(actual, expected)) {
    return { valid: false, error: "Invalid token signature" };
  }
  try {
    const payload = JSON.parse(base64UrlDecode(encodedPayload));
    const now = Math.floor(Date.now() / 1e3);
    if (payload.exp && payload.exp < now) {
      return { valid: false, error: "Token has expired" };
    }
    return { valid: true, payload };
  } catch (err) {
    return { valid: false, error: "Failed to decode token payload" };
  }
}
var ROLE_PERMISSIONS = {
  ADMIN: [
    "medicine.view",
    "medicine.create",
    "medicine.edit",
    "medicine.delete",
    "medicine.change_price",
    "inventory.view",
    "inventory.adjust",
    "stock.receive",
    "sales.create",
    "sales.view_own",
    "sales.view_all",
    "sales.void",
    "returns.create",
    "returns.approve",
    "reports.view",
    "users.manage",
    "audit.view",
    "settings.manage",
    "suppliers.manage",
    "expenses.manage",
    "devices.manage"
  ],
  MANAGER: [
    "medicine.view",
    "medicine.edit",
    "inventory.view",
    "stock.receive",
    "sales.create",
    "sales.view_own",
    "sales.view_all",
    "returns.create",
    "returns.approve",
    "reports.view",
    "suppliers.manage",
    "expenses.manage",
    "customers.manage"
  ],
  CASHIER: [
    "medicine.view",
    "sales.create",
    "sales.view_own",
    "returns.create",
    "customers.manage"
  ]
};
function hasPermission(role, permissionKey) {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permissionKey);
}

// server/db/client.ts
import pg from "pg";
import dotenv from "dotenv";
dotenv.config();
var { Pool } = pg;
pg.types.setTypeParser(1082, (value) => value);
function getAppMode() {
  const envMode = (process.env.APP_MODE || "").toLowerCase().trim();
  if (envMode === "online") return "online";
  if (envMode === "cloud") return "cloud";
  if (envMode === "hybrid") return "hybrid";
  if (envMode === "local") return "local";
  if (process.env.DATABASE_URL && process.env.SUPABASE_URL) return "hybrid";
  if (process.env.DATABASE_URL) return "local";
  if (process.env.SUPABASE_URL) return "cloud";
  return "local";
}
function getDatabaseConnectionConfig() {
  const connStr = process.env.LOCAL_DATABASE_URL || process.env.DATABASE_URL;
  if (connStr) {
    const isSsl2 = connStr.includes("supabase.co") || connStr.includes("sslmode=require") || process.env.DB_SSL === "true";
    return {
      connectionString: connStr,
      ssl: isSsl2 ? { rejectUnauthorized: false } : void 0,
      max: 20,
      idleTimeoutMillis: 3e4,
      connectionTimeoutMillis: 5e3
    };
  }
  const host = process.env.DB_HOST || "127.0.0.1";
  const port = parseInt(process.env.DB_PORT || "5432", 10);
  const database = process.env.DB_NAME || "giga_chemist";
  const user = process.env.DB_USER || "postgres";
  const password = process.env.DB_PASSWORD || "postgres";
  const isSsl = process.env.DB_SSL === "true";
  return {
    host,
    port,
    database,
    user,
    password,
    ssl: isSsl ? { rejectUnauthorized: false } : void 0,
    max: 20,
    idleTimeoutMillis: 3e4,
    connectionTimeoutMillis: 5e3
  };
}
var supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
var supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
var pgPool = new Pool(getDatabaseConnectionConfig());
var _supabaseAdminInstance = null;
var isSupabaseConfigured = Boolean(
  supabaseUrl && supabaseServiceKey && !supabaseUrl.includes("placeholder")
);
var supabaseAdmin = new Proxy({}, {
  get(target, prop) {
    if (!isSupabaseConfigured) {
      return () => {
        throw new Error("Supabase is not configured in local development mode.");
      };
    }
    if (!_supabaseAdminInstance) {
      throw new Error("Supabase cloud operations are disabled in local mode.");
    }
    return _supabaseAdminInstance[prop];
  }
});
var isLocalMode = getAppMode() === "local";
var isCloudMode = getAppMode() === "cloud";
var isHybridMode = getAppMode() === "hybrid";
function isValidUuid(id) {
  if (!id || typeof id !== "string") return false;
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id.trim());
}
var HttpError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
function requireUuid(id, field) {
  if (typeof id !== "string" || !isValidUuid(id)) {
    throw new HttpError(400, `${field} must be a valid UUID.`);
  }
  return id.trim();
}
async function businessNow(q = pgPool) {
  const res = await q.query(
    `SELECT to_char(now() AT TIME ZONE 'Africa/Nairobi', 'YYYY-MM-DD') AS date,
            to_char(now() AT TIME ZONE 'Africa/Nairobi', 'HH24:MI:SS') AS time`
  );
  return { date: res.rows[0].date, time: res.rows[0].time };
}

// server/db/reports.ts
var DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
var cents = (v) => Math.round(Number(v || 0) * 100) / 100;
async function resolveRange(range, start, end, q = pgPool) {
  const r = typeof range === "string" && range ? range : "today";
  const d = (await q.query(`
    SELECT to_char((now() AT TIME ZONE 'Africa/Nairobi')::date, 'YYYY-MM-DD') AS today,
           to_char(date_trunc('week', now() AT TIME ZONE 'Africa/Nairobi')::date, 'YYYY-MM-DD') AS week_start,
           to_char(date_trunc('month', now() AT TIME ZONE 'Africa/Nairobi')::date, 'YYYY-MM-DD') AS month_start`)).rows[0];
  if (r === "today") return { range: r, start: d.today, end: d.today, today: d.today };
  if (r === "week") return { range: r, start: d.week_start, end: d.today, today: d.today };
  if (r === "month") return { range: r, start: d.month_start, end: d.today, today: d.today };
  if (r === "custom") {
    if (typeof start !== "string" || !DATE_RE.test(start) || typeof end !== "string" || !DATE_RE.test(end)) {
      throw new HttpError(400, "Custom range needs start and end as YYYY-MM-DD.");
    }
    if (start > end) throw new HttpError(400, "start must not be after end.");
    const days = (Date.parse(end) - Date.parse(start)) / 864e5;
    if (days > 3700) throw new HttpError(400, "Custom range is limited to 10 years.");
    return { range: r, start, end, today: d.today };
  }
  throw new HttpError(400, "range must be today, week, month or custom.");
}
async function getStockCounts(q = pgPool) {
  const r = (await q.query(`
    SELECT COUNT(*)::int AS total,
           COUNT(*) FILTER (WHERE current_stock > 0)::int AS in_stock,
           COUNT(*) FILTER (WHERE current_stock > 0 AND current_stock <= COALESCE(reorder_level, 0))::int AS low_stock,
           COUNT(*) FILTER (WHERE current_stock <= 0)::int AS out_of_stock
      FROM medicines WHERE COALESCE(status, 'active') = 'active'`)).rows[0];
  return { totalMedicines: r.total, inStock: r.in_stock, lowStock: r.low_stock, outOfStock: r.out_of_stock };
}
async function getSalesReport(rangeIn, scope, q = pgPool) {
  const { start, end } = rangeIn;
  const cashierId = scope.cashierId ? requireUuid(scope.cashierId, "cashierId") : null;
  const p = [start, end];
  const saleScope = cashierId ? (p.push(cashierId), `AND s.cashier_id = $3`) : "";
  const totals = (await q.query(
    `SELECT COALESCE(SUM(s.total) FILTER (WHERE s.status <> 'voided'), 0) AS gross,
            COALESCE(SUM(s.discount_total) FILTER (WHERE s.status <> 'voided'), 0) AS discounts,
            COALESCE(SUM(s.cost_total) FILTER (WHERE s.status <> 'voided'), 0) AS cogs,
            COUNT(*) FILTER (WHERE s.status <> 'voided')::int AS txn,
            COUNT(*) FILTER (WHERE s.status = 'voided')::int AS void_count,
            COALESCE(SUM(s.total) FILTER (WHERE s.status = 'voided'), 0) AS void_total
       FROM sales s WHERE s.date BETWEEN $1::date AND $2::date ${saleScope}`,
    p
  )).rows[0];
  const units = (await q.query(
    `SELECT COALESCE(SUM(si.quantity), 0)::int AS units
       FROM sale_items si JOIN sales s ON s.id = si.sale_id
      WHERE s.status <> 'voided' AND s.date BETWEEN $1::date AND $2::date ${saleScope}`,
    p
  )).rows[0];
  const approvedReturns = `
    FROM returns r JOIN sales s ON s.id = r.sale_id
    WHERE r.status = 'APPROVED'
      AND (COALESCE(r.reviewed_at, r.created_at) AT TIME ZONE 'Africa/Nairobi')::date BETWEEN $1::date AND $2::date ${saleScope}`;
  const refunds = (await q.query(
    `SELECT COALESCE(SUM(r.refund_amount), 0) AS refunds, COUNT(*)::int AS n,
            COALESCE(SUM(COALESCE(r.approved_quantity, r.quantity)), 0)::int AS units,
            COALESCE(SUM(COALESCE(r.approved_quantity, r.quantity) * COALESCE((
              SELECT si.cost_price_snapshot FROM sale_items si
               WHERE si.sale_id = r.sale_id AND si.medicine_id = r.medicine_id AND si.batch_id = r.batch_id LIMIT 1), 0)), 0) AS cogs
     ${approvedReturns}`,
    p
  )).rows[0];
  const tenders = await q.query(
    `SELECT p.method, COALESCE(SUM(p.amount), 0) AS amount
       FROM payments p JOIN sales s ON s.id = p.sale_id
      WHERE s.status <> 'voided' AND s.date BETWEEN $1::date AND $2::date ${saleScope}
      GROUP BY p.method`,
    p
  );
  const tenderStats = { Cash: 0, "M-Pesa": 0, Card: 0, Bank: 0 };
  for (const t of tenders.rows) {
    const m = String(t.method || "").toLowerCase().replace(/[\s_-]/g, "") === "mpesa" ? "M-Pesa" : t.method;
    tenderStats[m] = cents((tenderStats[m] || 0) + Number(t.amount));
  }
  const refundTenders = await q.query(
    `SELECT CASE WHEN s.payment_method = 'Mixed' THEN 'Cash' ELSE s.payment_method END AS method,
            COALESCE(SUM(r.refund_amount), 0) AS amount ${approvedReturns} GROUP BY 1`,
    p
  );
  for (const t of refundTenders.rows) {
    if (tenderStats[t.method] !== void 0) tenderStats[t.method] = cents(Math.max(0, tenderStats[t.method] - Number(t.amount)));
  }
  const cashiers = await q.query(
    `WITH sold AS (
       SELECT s.cashier_id, COUNT(*)::int AS n, SUM(s.total) AS gross, SUM(s.gross_profit) AS profit
         FROM sales s WHERE s.status <> 'voided' AND s.date BETWEEN $1::date AND $2::date ${saleScope}
        GROUP BY s.cashier_id),
     ref AS (
       SELECT s.cashier_id, SUM(r.refund_amount) AS refunds,
              SUM(r.refund_amount - COALESCE(r.approved_quantity, r.quantity) * COALESCE((
                SELECT si.cost_price_snapshot FROM sale_items si
                 WHERE si.sale_id = r.sale_id AND si.medicine_id = r.medicine_id AND si.batch_id = r.batch_id LIMIT 1), 0)) AS lost_profit
       ${approvedReturns} GROUP BY s.cashier_id)
     SELECT COALESCE(u.name, 'Unknown') AS name, COALESCE(sold.n, 0) AS n, COALESCE(sold.gross, 0) AS gross,
            COALESCE(ref.refunds, 0) AS refunds, COALESCE(sold.profit, 0) - COALESCE(ref.lost_profit, 0) AS profit
       FROM sold FULL JOIN ref ON ref.cashier_id = sold.cashier_id
       LEFT JOIN users u ON u.id = COALESCE(sold.cashier_id, ref.cashier_id)
      ORDER BY 3 DESC`,
    p
  );
  const cashierStats = {};
  for (const c of cashiers.rows) {
    const prev = cashierStats[c.name] || { count: 0, gross: 0, refunds: 0, net: 0, profit: 0 };
    prev.count += Number(c.n);
    prev.gross = cents(prev.gross + Number(c.gross));
    prev.refunds = cents(prev.refunds + Number(c.refunds));
    prev.net = cents(prev.gross - prev.refunds);
    prev.profit = scope.includeCost ? cents(prev.profit + Number(c.profit)) : 0;
    cashierStats[c.name] = prev;
  }
  const medicines = await q.query(
    `WITH sold AS (
       SELECT si.medicine_id, SUM(si.quantity) AS qty, SUM(si.total) AS revenue,
              SUM(si.total - si.quantity * COALESCE(si.cost_price_snapshot, 0)) AS profit
         FROM sale_items si JOIN sales s ON s.id = si.sale_id
        WHERE s.status <> 'voided' AND s.date BETWEEN $1::date AND $2::date ${saleScope}
        GROUP BY si.medicine_id),
     ref AS (
       SELECT r.medicine_id, SUM(COALESCE(r.approved_quantity, r.quantity)) AS qty, SUM(r.refund_amount) AS revenue
       ${approvedReturns} GROUP BY r.medicine_id)
     SELECT COALESCE(m.name, 'Unknown medicine') AS name,
            COALESCE(sold.qty, 0) - COALESCE(ref.qty, 0) AS quantity,
            COALESCE(sold.revenue, 0) - COALESCE(ref.revenue, 0) AS revenue,
            COALESCE(sold.profit, 0) AS profit
       FROM sold FULL JOIN ref ON ref.medicine_id = sold.medicine_id
       LEFT JOIN medicines m ON m.id = COALESCE(sold.medicine_id, ref.medicine_id)
      ORDER BY 2 DESC, 3 DESC LIMIT 200`,
    p
  );
  const returnsList = await q.query(
    `SELECT r.id, r.receipt_number,
            to_char((COALESCE(r.reviewed_at, r.created_at) AT TIME ZONE 'Africa/Nairobi')::date, 'YYYY-MM-DD') AS date,
            COALESCE(m.name, '') AS medicine_name, COALESCE(b.batch_number, '') AS batch_number,
            COALESCE(r.approved_quantity, r.quantity) AS quantity, r.refund_amount, r.reason, r.action
     ${approvedReturns.replace(
      "FROM returns r JOIN sales s ON s.id = r.sale_id",
      "FROM returns r JOIN sales s ON s.id = r.sale_id LEFT JOIN medicines m ON m.id = r.medicine_id LEFT JOIN medicine_batches b ON b.id = r.batch_id"
    )}
      ORDER BY COALESCE(r.reviewed_at, r.created_at) DESC LIMIT 1000`,
    p
  );
  let expenses = [];
  let expenseCategoryStats = {};
  let operatingExpenses = 0;
  let purchases = { count: 0, total: 0 };
  if (scope.includeCost) {
    const ex = await q.query(
      `SELECT e.id, to_char(e.date, 'YYYY-MM-DD') AS date, e.category, e.description, e.payment_method, e.amount,
              COALESCE(u.name, '') AS user_name
         FROM expenses e LEFT JOIN users u ON u.id = e.user_id
        WHERE e.date BETWEEN $1::date AND $2::date ORDER BY e.date DESC, e.created_at DESC`,
      [start, end]
    );
    expenses = ex.rows.map((e) => ({ ...e, amount: cents(e.amount) }));
    for (const e of expenses) {
      expenseCategoryStats[e.category] = cents((expenseCategoryStats[e.category] || 0) + e.amount);
      operatingExpenses = cents(operatingExpenses + e.amount);
    }
    const pu = (await q.query(
      `SELECT COUNT(*)::int AS n, COALESCE(SUM(total_amount), 0) AS total FROM purchases
        WHERE COALESCE(received_date, order_date) BETWEEN $1::date AND $2::date`,
      [start, end]
    )).rows[0];
    purchases = { count: pu.n, total: cents(pu.total) };
  }
  const gross = cents(totals.gross);
  const refundTotal = cents(refunds.refunds);
  const netSales = cents(gross - refundTotal);
  const netCogs = cents(Math.max(0, Number(totals.cogs) - Number(refunds.cogs)));
  const grossProfit = cents(netSales - netCogs);
  const netProfit = cents(grossProfit - operatingExpenses);
  return {
    range: rangeIn.range,
    start,
    end,
    today: rangeIn.today,
    scope: cashierId ? "cashier" : "all",
    grossSales: gross,
    discounts: cents(totals.discounts),
    refunds: refundTotal,
    refundCount: refunds.n,
    netSales,
    cash: tenderStats.Cash || 0,
    mpesa: tenderStats["M-Pesa"] || 0,
    tenders: tenderStats,
    voids: { count: totals.void_count, total: cents(totals.void_total) },
    transactionCount: totals.txn,
    unitsSold: units.units,
    unitsReturned: refunds.units,
    netCogs: scope.includeCost ? netCogs : 0,
    grossProfit: scope.includeCost ? grossProfit : 0,
    grossMarginPercent: scope.includeCost && netSales > 0 ? Math.round(grossProfit / netSales * 1e3) / 10 : 0,
    operatingExpenses,
    netProfit: scope.includeCost ? netProfit : 0,
    netMarginPercent: scope.includeCost && netSales > 0 ? Math.round(netProfit / netSales * 1e3) / 10 : 0,
    purchases,
    expenses,
    expenseCategoryStats,
    cashierStats,
    medicines: medicines.rows.map((m) => ({
      name: m.name,
      quantity: Number(m.quantity),
      revenue: cents(m.revenue),
      profit: scope.includeCost ? cents(m.profit) : 0
    })),
    returns: returnsList.rows.map((r) => ({ ...r, quantity: Number(r.quantity), refund_amount: cents(r.refund_amount) })),
    stock: await getStockCounts(q)
  };
}

// server/db/sales.ts
var toCents = (n) => Math.round(Number(n) * 100);
var fromCents = (c) => c / 100;
var PAYMENT_METHODS = ["Cash", "M-Pesa", "Card", "Bank", "Mixed"];
var PRICE_MODES = ["RETAIL", "WHOLESALE"];
function requirePriceMode(value, field) {
  if (value === void 0 || value === null || value === "") return "RETAIL";
  if (!PRICE_MODES.includes(value)) throw new HttpError(400, `${field} must be RETAIL or WHOLESALE.`);
  return value;
}
var SALE_COLUMNS = `
  s.id, s.branch_id, s.sale_number, s.receipt_number,
  s.cashier_id, u.name AS cashier_name,
  s.customer_id, c.name AS customer_name, c.phone AS customer_phone,
  s.device_id, s.date, s.time,
  COALESCE(s.subtotal, 0)::float AS subtotal,
  COALESCE(s.discount_percent, 0)::float AS discount_percent,
  COALESCE(s.discount_total, 0)::float AS discount_total,
  COALESCE(s.tax_total, 0)::float AS tax_total,
  COALESCE(s.total, 0)::float AS total,
  COALESCE(s.cost_total, 0)::float AS cost_total,
  COALESCE(s.gross_profit, 0)::float AS gross_profit,
  s.payment_method, s.payment_reference,
  COALESCE(s.amount_received, 0)::float AS amount_received,
  COALESCE(s.change_given, 0)::float AS change_given,
  s.status, s.void_reason, s.voided_by, s.idempotency_key, s.price_mode, s.created_at`;
async function hydrateSales(q, rows) {
  if (rows.length === 0) return [];
  const ids = rows.map((r) => r.id);
  const [items, payments, returned] = await Promise.all([
    q.query(
      `SELECT si.id, si.sale_id, si.medicine_id, m.name AS medicine_name, m.generic_name,
              si.batch_id, si.batch_number, si.expiry_date,
              si.quantity::int AS quantity, si.unit_price::float AS unit_price, COALESCE(si.discount, 0)::float AS discount,
              si.cost_price_snapshot::float AS cost_price_snapshot, si.total::float AS total, si.price_mode
       FROM sale_items si LEFT JOIN medicines m ON si.medicine_id = m.id
       WHERE si.sale_id = ANY($1::uuid[])
       ORDER BY si.created_at, si.id`,
      [ids]
    ),
    q.query(
      `SELECT sale_id, method, amount::float AS amount, reference FROM payments
       WHERE sale_id = ANY($1::uuid[]) ORDER BY created_at, id`,
      [ids]
    ),
    q.query(
      `SELECT sale_id, medicine_id, batch_id,
              COALESCE(SUM(approved_quantity) FILTER (WHERE status = 'APPROVED'), 0)::int AS qty,
              COALESCE(SUM(quantity) FILTER (WHERE status = 'PENDING'), 0)::int AS pending,
              COALESCE(SUM(refund_amount) FILTER (WHERE status = 'APPROVED'), 0)::float AS refunded
       FROM returns WHERE sale_id = ANY($1::uuid[]) GROUP BY sale_id, medicine_id, batch_id`,
      [ids]
    )
  ]);
  const itemsBySale = /* @__PURE__ */ new Map();
  for (const it of items.rows) {
    const list = itemsBySale.get(it.sale_id) || [];
    list.push({
      id: it.id,
      medicine_id: it.medicine_id,
      medicine_name: it.medicine_name || "Pharmaceutical Item",
      generic_name: it.generic_name || "",
      batch_id: it.batch_id,
      batch_number: it.batch_number,
      expiry_date: it.expiry_date || "",
      quantity: Number(it.quantity) || 0,
      unit_price: Number(it.unit_price) || 0,
      discount: Number(it.discount) || 0,
      cost_price_snapshot: Number(it.cost_price_snapshot) || 0,
      total: Number(it.total) || 0,
      price_mode: it.price_mode || null
    });
    itemsBySale.set(it.sale_id, list);
  }
  const paymentsBySale = /* @__PURE__ */ new Map();
  for (const p of payments.rows) {
    const list = paymentsBySale.get(p.sale_id) || [];
    list.push({ method: p.method, amount: Number(p.amount) || 0, reference: p.reference || void 0 });
    paymentsBySale.set(p.sale_id, list);
  }
  const returnedBySale = /* @__PURE__ */ new Map();
  for (const r of returned.rows) {
    const list = returnedBySale.get(r.sale_id) || [];
    list.push({ medicine_id: r.medicine_id, batch_id: r.batch_id, quantity: Number(r.qty) || 0, pending: Number(r.pending) || 0, refunded: Number(r.refunded) || 0 });
    returnedBySale.set(r.sale_id, list);
  }
  return rows.map((r) => {
    const pays = paymentsBySale.get(r.id) || [];
    return {
      id: r.id,
      branch_id: r.branch_id || void 0,
      sale_number: r.sale_number,
      receipt_number: r.receipt_number,
      date: r.date || "",
      time: r.time || "",
      timestamp: r.created_at ? new Date(r.created_at).getTime() : Date.now(),
      cashier_id: r.cashier_id,
      cashier_name: r.cashier_name || "Cashier",
      customer_id: r.customer_id || void 0,
      customer_name: r.customer_name || "Walk-in",
      customer_phone: r.customer_phone || void 0,
      device_id: r.device_id,
      items: itemsBySale.get(r.id) || [],
      price_mode: r.price_mode || null,
      subtotal: Number(r.subtotal) || 0,
      discount_percent: Number(r.discount_percent) || 0,
      discount_total: Number(r.discount_total) || 0,
      tax_total: Number(r.tax_total) || 0,
      total: Number(r.total) || 0,
      cost_total: Number(r.cost_total) || 0,
      gross_profit: Number(r.gross_profit) || 0,
      payment_method: r.payment_method || "Cash",
      payment_reference: r.payment_reference || void 0,
      amount_received: Number(r.amount_received) || 0,
      change_given: Number(r.change_given) || 0,
      split_payments: r.payment_method === "Mixed" ? pays : void 0,
      status: r.status || "completed",
      void_reason: r.void_reason || void 0,
      voided_by: r.voided_by || void 0,
      sync_status: "synced",
      retry_count: 0,
      idempotency_key: r.idempotency_key,
      returned_items: returnedBySale.get(r.id) || []
    };
  });
}
var SALE_STATUSES = ["completed", "partially_returned", "returned", "voided"];
var DATE_RE2 = /^\d{4}-\d{2}-\d{2}$/;
async function getAllSales(params, q = pgPool) {
  const page = Math.max(1, Number(params?.page) || 1);
  const limit = Math.min(500, Math.max(1, Number(params?.limit) || 50));
  const offset = (page - 1) * limit;
  const conditions = [];
  const values = [];
  if (params?.search?.trim()) {
    values.push(`%${params.search.trim()}%`);
    conditions.push(`(s.receipt_number ILIKE $${values.length} OR s.sale_number ILIKE $${values.length} OR s.payment_reference ILIKE $${values.length} OR c.name ILIKE $${values.length})`);
  }
  if (params?.startDate) {
    if (!DATE_RE2.test(params.startDate)) throw new HttpError(400, "startDate must be YYYY-MM-DD.");
    values.push(params.startDate);
    conditions.push(`s.date >= $${values.length}`);
  }
  if (params?.endDate) {
    if (!DATE_RE2.test(params.endDate)) throw new HttpError(400, "endDate must be YYYY-MM-DD.");
    values.push(params.endDate);
    conditions.push(`s.date <= $${values.length}`);
  }
  if (params?.cashierId) {
    values.push(requireUuid(params.cashierId, "cashierId"));
    conditions.push(`s.cashier_id = $${values.length}`);
  }
  if (params?.paymentMethod) {
    if (!PAYMENT_METHODS.includes(params.paymentMethod)) throw new HttpError(400, `paymentMethod must be one of ${PAYMENT_METHODS.join(", ")}.`);
    values.push(params.paymentMethod);
    conditions.push(`(s.payment_method = $${values.length} OR EXISTS (SELECT 1 FROM payments px WHERE px.sale_id = s.id AND px.method = $${values.length}))`);
  }
  if (params?.customerId) {
    values.push(requireUuid(params.customerId, "customerId"));
    conditions.push(`s.customer_id = $${values.length}`);
  }
  if (params?.priceMode) {
    const mode = requirePriceMode(params.priceMode, "priceMode");
    values.push(mode);
    conditions.push(`COALESCE(s.price_mode, 'RETAIL') = $${values.length}`);
  }
  if (params?.status) {
    if (params.status === "not_voided") conditions.push(`s.status <> 'voided'`);
    else {
      if (!SALE_STATUSES.includes(params.status)) throw new HttpError(400, `status must be one of ${SALE_STATUSES.join(", ")}, not_voided.`);
      values.push(params.status);
      conditions.push(`s.status = $${values.length}`);
    }
  }
  const where = conditions.length ? `WHERE ${conditions.join(" AND ")}` : "";
  const from = `FROM sales s LEFT JOIN users u ON s.cashier_id = u.id LEFT JOIN customers c ON s.customer_id = c.id`;
  const count = await q.query(`SELECT COUNT(*)::int AS n ${from} ${where}`, values);
  const rows = await q.query(
    `SELECT ${SALE_COLUMNS} ${from} ${where} ORDER BY s.created_at DESC, s.id DESC LIMIT $${values.length + 1} OFFSET $${values.length + 2}`,
    [...values, limit, offset]
  );
  const sales = await hydrateSales(q, rows.rows);
  if (params?.page || params?.limit) {
    const total = count.rows[0].n;
    return { sales, total, page, limit, totalPages: Math.ceil(total / limit) || 1 };
  }
  return sales;
}
async function getTodaySalesSummary(options, q = pgPool) {
  const cashierId = options.cashierId ? requireUuid(options.cashierId, "cashierId") : null;
  const { date: today } = await businessNow(q);
  const params = [today];
  const cashierFilter = cashierId ? (params.push(cashierId), `AND s.cashier_id = $2`) : "";
  const totals = await q.query(
    `SELECT COALESCE(SUM(s.total) FILTER (WHERE s.status <> 'voided'), 0)::numeric AS total_sales,
            COALESCE(SUM(s.discount_total) FILTER (WHERE s.status <> 'voided'), 0)::numeric AS discount_total,
            COALESCE(SUM(s.gross_profit) FILTER (WHERE s.status <> 'voided'), 0)::numeric AS gross_profit,
            COUNT(*) FILTER (WHERE s.status <> 'voided')::int AS txn,
            COUNT(*) FILTER (WHERE s.status = 'voided')::int AS voided
     FROM sales s WHERE s.date = $1::date ${cashierFilter}`,
    params
  );
  const pays = await q.query(
    `SELECT p.method, COALESCE(SUM(p.amount), 0)::numeric AS amount
     FROM payments p JOIN sales s ON p.sale_id = s.id
     WHERE s.date = $1::date AND s.status <> 'voided' ${cashierFilter}
     GROUP BY p.method`,
    params
  );
  const refundFilter = cashierId ? `AND r.user_id = $2` : "";
  const refunds = await q.query(
    // Only APPROVED returns are refunds; counted on the day the Administrator approved them.
    `SELECT COALESCE(SUM(r.refund_amount), 0)::numeric AS refunds
     FROM returns r WHERE r.status = 'APPROVED' AND (r.reviewed_at AT TIME ZONE 'Africa/Nairobi')::date = $1::date ${refundFilter}`,
    params
  );
  let cash = 0;
  let mpesa = 0;
  let other = 0;
  for (const row of pays.rows) {
    const cents2 = toCents(row.amount);
    const m = String(row.method || "").toLowerCase().replace(/[\s_-]/g, "");
    if (m === "cash") cash += cents2;
    else if (m === "mpesa") mpesa += cents2;
    else other += cents2;
  }
  const totalSales = toCents(totals.rows[0].total_sales);
  const refundCents = toCents(refunds.rows[0].refunds);
  return {
    date: today,
    scope: cashierId ? "cashier" : "all",
    totalSales: fromCents(totalSales),
    cashTotal: fromCents(cash),
    mpesaTotal: fromCents(mpesa),
    otherTotal: fromCents(other),
    transactionCount: Number(totals.rows[0].txn) || 0,
    discountTotal: fromCents(toCents(totals.rows[0].discount_total)),
    refundsTotal: fromCents(refundCents),
    netSales: fromCents(totalSales - refundCents),
    voidedCount: Number(totals.rows[0].voided) || 0,
    grossProfit: fromCents(toCents(totals.rows[0].gross_profit))
  };
}

// server/db/medicines.ts
var MEDICINE_SELECT = `
  SELECT
    m.id, m.branch_id, m.name, m.generic_name, m.brand_name, m.sku, m.barcode,
    COALESCE(c.name, m.medicine_type, 'General') AS category,
    m.medicine_type, m.dosage_strength, m.dosage_form, m.manufacturer, m.description,
    COALESCE(m.purchase_price, 0)::float AS purchase_price,
    COALESCE(m.selling_price, 0)::float AS selling_price,
    m.wholesale_price::float AS wholesale_price,
    COALESCE(m.min_selling_price, m.selling_price, 0)::float AS min_selling_price,
    COALESCE(m.current_stock, 0)::int AS current_stock,
    COALESCE(m.reorder_level, 20)::int AS reorder_level,
    COALESCE(m.unit, 'Unit') AS unit,
    COALESCE(m.prescription_required, false) AS prescription_required,
    COALESCE(m.status, 'active') AS status,
    COALESCE(m.version, 1)::int AS version,
    m.created_at, m.updated_at
  FROM medicines m
  LEFT JOIN categories c ON m.category_id = c.id`;
function toMedicine(r) {
  return {
    id: r.id,
    branch_id: r.branch_id || void 0,
    name: r.name,
    generic_name: r.generic_name || r.name,
    brand_name: r.brand_name || "",
    sku: r.sku || "",
    barcode: r.barcode || "",
    category: r.category || "General",
    medicine_type: r.medicine_type || "",
    dosage_strength: r.dosage_strength || "",
    dosage_form: r.dosage_form || "Tablet",
    manufacturer: r.manufacturer || "",
    description: r.description || "",
    purchase_price: Number(r.purchase_price) || 0,
    selling_price: Number(r.selling_price) || 0,
    // NULL = no wholesale price set. Never substituted with the retail price.
    wholesale_price: r.wholesale_price != null ? Number(r.wholesale_price) : null,
    min_selling_price: Number(r.min_selling_price) || 0,
    current_stock: Number(r.current_stock) || 0,
    reorder_level: Number(r.reorder_level) || 0,
    unit: r.unit || "Unit",
    prescription_required: Boolean(r.prescription_required),
    status: r.status || "active",
    version: Number(r.version) || 1,
    created_at: r.created_at ? new Date(r.created_at).toISOString() : "",
    updated_at: r.updated_at ? new Date(r.updated_at).toISOString() : "",
    created_by: "Admin",
    updated_by: "Admin"
  };
}
async function getAllMedicines(q = pgPool) {
  const res = await q.query(`${MEDICINE_SELECT} ORDER BY m.name ASC`);
  return res.rows.map(toMedicine);
}

// server/db/batches.ts
var BATCH_SELECT = `
  SELECT b.id, b.branch_id, b.medicine_id, COALESCE(m.name, 'Pharmaceutical Item') AS medicine_name,
         b.batch_number, b.supplier_id, COALESCE(s.name, '') AS supplier_name,
         COALESCE(b.quantity_received, 0)::int AS quantity_received,
         COALESCE(b.quantity_available, 0)::int AS quantity_available,
         COALESCE(b.purchase_price, 0)::float AS purchase_price,
         b.selling_price_override::float AS selling_price_override,
         b.manufacturing_date, b.expiry_date, b.received_date, b.purchase_invoice, b.expiry_status,
         COALESCE(b.status, 'active') AS status, b.created_at
  FROM medicine_batches b
  LEFT JOIN medicines m ON b.medicine_id = m.id
  LEFT JOIN suppliers s ON b.supplier_id = s.id`;
function toBatch(r) {
  return {
    id: r.id,
    branch_id: r.branch_id || void 0,
    medicine_id: r.medicine_id,
    medicine_name: r.medicine_name,
    batch_number: r.batch_number,
    supplier_id: r.supplier_id || "",
    supplier_name: r.supplier_name || "",
    quantity_received: Number(r.quantity_received) || 0,
    quantity_available: Number(r.quantity_available) || 0,
    purchase_price: Number(r.purchase_price) || 0,
    selling_price_override: r.selling_price_override != null ? Number(r.selling_price_override) : void 0,
    manufacturing_date: r.manufacturing_date || "",
    expiry_date: r.expiry_date || "",
    expiry_status: r.expiry_status || (r.expiry_date ? "KNOWN" : "UNKNOWN"),
    received_date: r.received_date || "",
    purchase_invoice: r.purchase_invoice || "",
    created_by: "Admin",
    created_at: r.created_at ? new Date(r.created_at).toISOString() : "",
    status: r.status || "active"
  };
}
async function getAllBatches(q = pgPool) {
  const res = await q.query(`${BATCH_SELECT} ORDER BY b.expiry_date ASC NULLS LAST, b.created_at ASC`);
  return res.rows.map(toBatch);
}

// server/db/categories.ts
async function getAllCategories(q = pgPool) {
  const res = await q.query(`SELECT id, name, description, created_at, updated_at FROM categories ORDER BY name ASC`);
  return res.rows.map((r) => ({
    id: r.id,
    name: r.name,
    description: r.description || void 0,
    created_at: r.created_at ? new Date(r.created_at).toISOString() : void 0,
    updated_at: r.updated_at ? new Date(r.updated_at).toISOString() : void 0
  }));
}

// server/db/returns.ts
var RETURN_SELECT = `
  SELECT r.id, r.branch_id, r.sale_id, r.receipt_number, r.medicine_id, m.name AS medicine_name,
         r.batch_id, b.batch_number, r.quantity::int AS quantity, r.unit_price::float AS unit_price,
         r.refund_amount::float AS refund_amount, r.requested_refund::float AS requested_refund,
         r.approved_quantity, r.restocked, r.reason, r.action, r.status,
         r.user_id, u.name AS user_name, r.device_id, r.created_at,
         r.reviewed_by, rv.name AS reviewed_by_name, r.reviewed_at, r.review_notes,
         s.date AS sale_date, s.time AS sale_time, s.status AS sale_status, s.price_mode AS sale_price_mode,
         COALESCE(s.discount_percent, 0)::float AS sale_discount_percent,
         c.name AS customer_name,
         li.sold_qty, li.sold_total, li.line_discount,
         (SELECT COALESCE(SUM(r2.approved_quantity), 0) FROM returns r2
           WHERE r2.sale_id = r.sale_id AND r2.medicine_id = r.medicine_id AND r2.batch_id = r.batch_id
             AND r2.status = 'APPROVED' AND r2.id <> r.id)::int AS other_approved_qty
  FROM returns r
  JOIN sales s ON s.id = r.sale_id
  LEFT JOIN customers c ON c.id = s.customer_id
  LEFT JOIN medicines m ON m.id = r.medicine_id
  LEFT JOIN medicine_batches b ON b.id = r.batch_id
  LEFT JOIN users u ON u.id = r.user_id
  LEFT JOIN users rv ON rv.id = r.reviewed_by
  LEFT JOIN LATERAL (
    SELECT COALESCE(SUM(si.quantity), 0)::int AS sold_qty, COALESCE(SUM(si.total), 0)::float AS sold_total,
           COALESCE(SUM(si.discount), 0)::float AS line_discount
    FROM sale_items si
    WHERE si.sale_id = r.sale_id AND si.medicine_id = r.medicine_id AND si.batch_id = r.batch_id AND si.quantity > 0
  ) li ON true`;
function toReturn(r) {
  const paidPerUnit = r.sold_qty ? Math.round(r.sold_total / r.sold_qty * 100) / 100 : 0;
  return {
    id: r.id,
    branch_id: r.branch_id || void 0,
    sale_id: r.sale_id,
    receipt_number: r.receipt_number,
    medicine_id: r.medicine_id,
    medicine_name: r.medicine_name || "Item",
    batch_id: r.batch_id,
    batch_number: r.batch_number || "Batch",
    quantity: Number(r.quantity) || 0,
    unit_price: Number(r.unit_price) || 0,
    effective_unit_price: paidPerUnit,
    refund_amount: Number(r.refund_amount) || 0,
    requested_refund: r.requested_refund != null ? Number(r.requested_refund) : void 0,
    approved_quantity: r.approved_quantity ?? void 0,
    restocked: r.restocked ?? void 0,
    reason: r.reason,
    action: r.action,
    status: r.status,
    user_id: r.user_id,
    user_name: r.user_name || "Staff",
    device_id: r.device_id,
    reviewed_by: r.reviewed_by || void 0,
    reviewed_by_name: r.reviewed_by_name || void 0,
    reviewed_at: r.reviewed_at ? new Date(r.reviewed_at).toISOString() : void 0,
    review_notes: r.review_notes || void 0,
    sale_date: r.sale_date || "",
    sale_time: r.sale_time || "",
    sale_status: r.sale_status,
    sale_price_mode: r.sale_price_mode || null,
    sale_discount_percent: Number(r.sale_discount_percent) || 0,
    customer_name: r.customer_name || void 0,
    sold_quantity: Number(r.sold_qty) || 0,
    sold_total: Number(r.sold_total) || 0,
    sold_line_discount: Number(r.line_discount) || 0,
    other_approved_quantity: Number(r.other_approved_qty) || 0,
    date: r.created_at ? new Date(r.created_at).toLocaleDateString("en-CA", { timeZone: "Africa/Nairobi" }) : "",
    timestamp: r.created_at ? new Date(r.created_at).getTime() : Date.now(),
    sync_status: "synced"
  };
}
async function getAllReturns(options = {}, q = pgPool) {
  const where = [];
  const params = [];
  if (options.userId) {
    params.push(options.userId);
    where.push(`r.user_id = $${params.length}`);
  }
  if (options.status) {
    if (!["PENDING", "APPROVED", "REJECTED"].includes(options.status)) throw new HttpError(400, "status must be PENDING, APPROVED or REJECTED.");
    params.push(options.status);
    where.push(`r.status = $${params.length}`);
  }
  const res = await q.query(
    `${RETURN_SELECT} ${where.length ? "WHERE " + where.join(" AND ") : ""} ORDER BY r.created_at DESC LIMIT 1000`,
    params
  );
  return res.rows.map(toReturn);
}

// server/db/customers.ts
function toCustomer(r) {
  return {
    id: r.id,
    branch_id: r.branch_id || void 0,
    name: r.name,
    phone: r.phone || "",
    email: r.email || "",
    address: r.address || "",
    notes: r.notes || "",
    credit_balance: Number(r.credit_balance) || 0,
    total_spent: Number(r.total_spent) || 0,
    last_visit: r.last_visit ? new Date(r.last_visit).toISOString() : void 0,
    created_at: r.created_at ? new Date(r.created_at).toISOString() : ""
  };
}
async function getAllCustomers(q = pgPool) {
  const res = await q.query(
    "SELECT *, credit_balance::float AS credit_balance, total_spent::float AS total_spent FROM customers ORDER BY name ASC"
  );
  return res.rows.map(toCustomer);
}

// server/db/suppliers.ts
function toSupplier(r) {
  return {
    id: r.id,
    name: r.name,
    contact_person: r.contact_person || "",
    phone: r.phone || "",
    email: r.email || "",
    address: r.address || "",
    tax_pin: r.tax_pin || void 0,
    balance: Number(r.balance) || 0,
    status: r.status || "active",
    created_at: r.created_at ? new Date(r.created_at).toISOString() : ""
  };
}
async function getAllSuppliers(q = pgPool) {
  const res = await q.query("SELECT *, balance::float AS balance FROM suppliers ORDER BY name ASC");
  return res.rows.map(toSupplier);
}

// server/db/purchases.ts
var PURCHASE_SELECT = `
  SELECT p.id, p.branch_id, p.order_number, p.invoice_number, p.supplier_id, s.name AS supplier_name,
         p.order_date, p.received_date, p.status, COALESCE(p.total_amount, 0)::float AS total_amount,
         p.payment_status, p.notes, p.created_by, u.name AS created_by_name, p.created_at
  FROM purchases p
  LEFT JOIN suppliers s ON p.supplier_id = s.id
  LEFT JOIN users u ON p.created_by = u.id`;
async function hydratePurchases(q, rows) {
  if (rows.length === 0) return [];
  const items = await q.query(
    `SELECT pi.id, pi.purchase_id, pi.medicine_id, m.name AS medicine_name, pi.batch_number,
            pi.manufacturing_date, pi.expiry_date, pi.quantity::int AS quantity,
            pi.purchase_price::float AS purchase_price, pi.total::float AS total
     FROM purchase_items pi LEFT JOIN medicines m ON pi.medicine_id = m.id
     WHERE pi.purchase_id = ANY($1::uuid[]) ORDER BY pi.created_at, pi.id`,
    [rows.map((r) => r.id)]
  );
  const byPurchase = /* @__PURE__ */ new Map();
  for (const it of items.rows) {
    const list = byPurchase.get(it.purchase_id) || [];
    list.push({
      id: it.id,
      medicine_id: it.medicine_id,
      medicine_name: it.medicine_name || "Pharmaceutical Item",
      batch_number: it.batch_number,
      manufacturing_date: it.manufacturing_date || "",
      expiry_date: it.expiry_date || "",
      quantity: Number(it.quantity) || 0,
      purchase_price: Number(it.purchase_price) || 0,
      total: Number(it.total) || 0
    });
    byPurchase.set(it.purchase_id, list);
  }
  return rows.map((r) => ({
    id: r.id,
    branch_id: r.branch_id || void 0,
    order_number: r.order_number,
    invoice_number: r.invoice_number,
    supplier_id: r.supplier_id,
    supplier_name: r.supplier_name || "Supplier",
    order_date: r.order_date || "",
    received_date: r.received_date || void 0,
    status: r.status,
    total_amount: Number(r.total_amount) || 0,
    payment_status: r.payment_status || "unpaid",
    notes: r.notes || "",
    items: byPurchase.get(r.id) || [],
    created_by: r.created_by_name || "Admin",
    created_at: r.created_at ? new Date(r.created_at).toISOString() : "",
    sync_status: "synced"
  }));
}
async function getAllPurchases(q = pgPool) {
  const res = await q.query(`${PURCHASE_SELECT} ORDER BY p.order_date DESC, p.created_at DESC LIMIT 1000`);
  return hydratePurchases(q, res.rows);
}

// server/db/expenses.ts
function toExpense(r) {
  return {
    id: r.id,
    branch_id: r.branch_id || void 0,
    category: r.category,
    description: r.description,
    amount: Number(r.amount) || 0,
    payment_method: r.payment_method,
    reference: r.reference || void 0,
    user_id: r.user_id,
    user_name: r.user_name || "Staff",
    date: r.date || "",
    sync_status: "synced",
    created_at: r.created_at ? new Date(r.created_at).toISOString() : ""
  };
}
async function getAllExpenses(q = pgPool) {
  const res = await q.query(
    `SELECT e.*, e.amount::float AS amount, u.name AS user_name
     FROM expenses e LEFT JOIN users u ON e.user_id = u.id
     ORDER BY e.date DESC, e.created_at DESC LIMIT 2000`
  );
  return res.rows.map(toExpense);
}

// server/db/settings.ts
var MAIN_BRANCH_ID = "00000000-0000-0000-0000-000000000001";
function toSettings(r) {
  return {
    pharmacy_name: r.pharmacy_name,
    tagline: r.tagline || "",
    address: r.address || "",
    phone: r.phone || "",
    email: r.email || "",
    currency: r.currency || "KES",
    tax_rate: Number(r.tax_rate) || 0,
    tax_enabled: Boolean(r.tax_enabled),
    receipt_header: r.receipt_header || "",
    receipt_footer: r.receipt_footer || "",
    printer_type: r.printer_type === "58mm" ? "58mm" : "80mm",
    auto_print_receipt: Boolean(r.auto_print_receipt),
    low_stock_threshold: Number(r.low_stock_threshold) || 0,
    expiry_warning_days: Number(r.expiry_warning_days) || 0,
    require_prescription_warning: true,
    allow_walk_in: true,
    version: r.version || "1.0.0-pwa",
    updated_at: r.updated_at ? new Date(r.updated_at).toISOString() : ""
  };
}
async function ensureSettingsRow(q) {
  const existing = await q.query(
    `SELECT * FROM settings ORDER BY (branch_id = $1) DESC, updated_at DESC NULLS LAST LIMIT 1`,
    [MAIN_BRANCH_ID]
  );
  if (existing.rows[0]) return existing.rows[0];
  const created = await q.query(
    `INSERT INTO settings (branch_id) VALUES ($1) ON CONFLICT (branch_id) DO NOTHING RETURNING *`,
    [MAIN_BRANCH_ID]
  );
  return created.rows[0] || (await q.query("SELECT * FROM settings WHERE branch_id = $1", [MAIN_BRANCH_ID])).rows[0];
}
async function getPharmacySettings(q = pgPool) {
  return toSettings(await ensureSettingsRow(q));
}

// server/online/app.ts
var LOCAL_HOSTS = ["localhost", "127.0.0.1", "::1", "[::1]", "0.0.0.0"];
var SHOP_DATABASES = ["giga_chemist", "giga_chemist_dev"];
function getOnlineConfig() {
  const databaseUrl = (process.env.ONLINE_DATABASE_URL || process.env.DATABASE_URL || "").trim();
  const shopRaw = (process.env.SHOP_ID || "").trim();
  let error = null;
  if (!databaseUrl || /REQUIRED_USER_INPUT|YOUR_/i.test(databaseUrl)) error = "DATABASE_URL (cloud) is not configured.";
  else {
    try {
      const u = new URL(databaseUrl);
      const db = decodeURIComponent(u.pathname.replace(/^\//, ""));
      if (SHOP_DATABASES.includes(db)) error = `DATABASE_URL points to a shop database (${db}); the online API uses the cloud database only.`;
      else if (LOCAL_HOSTS.includes(u.hostname) && process.env.ONLINE_ALLOW_LOCAL_DB !== "true") {
        error = "DATABASE_URL points to localhost; the online API never uses a local PostgreSQL.";
      }
    } catch {
      error = "DATABASE_URL is not a valid URL.";
    }
  }
  if (!error && !isValidUuid(shopRaw)) error = "SHOP_ID (the registered shop UUID) is not configured.";
  return { databaseUrl, shopId: isValidUuid(shopRaw) ? shopRaw.toLowerCase() : null, error };
}
var pool = null;
function getPool(cfg) {
  if (pool) return pool;
  const u = new URL(cfg.databaseUrl);
  pool = new pg2.Pool({
    connectionString: cfg.databaseUrl,
    ssl: LOCAL_HOSTS.includes(u.hostname) ? void 0 : { rejectUnauthorized: false },
    max: Number(process.env.ONLINE_DB_POOL_MAX) || 3,
    idleTimeoutMillis: 1e4,
    connectionTimeoutMillis: 8e3
  });
  pool.on("error", (err) => console.error("[Online] database pool error:", err.message));
  return pool;
}
async function withShop(fn) {
  const cfg = getOnlineConfig();
  if (cfg.error) throw new HttpError(503, `Online API not configured: ${cfg.error}`);
  const client = await getPool(cfg).connect();
  try {
    await client.query("BEGIN READ ONLY");
    await client.query(`SELECT set_config('search_path', 'giga_online, pg_catalog', true), set_config('giga.shop_id', $1, true)`, [cfg.shopId]);
    const result = await fn(client);
    await client.query("COMMIT");
    return result;
  } catch (err) {
    await client.query("ROLLBACK").catch(() => {
    });
    throw err;
  } finally {
    client.release();
  }
}
async function withCloud(fn) {
  const cfg = getOnlineConfig();
  if (cfg.error) throw new HttpError(503, `Online API not configured: ${cfg.error}`);
  const client = await getPool(cfg).connect();
  try {
    return await fn(client);
  } finally {
    client.release();
  }
}
var version = "0.0.0";
try {
  version = JSON.parse(fs.readFileSync(path.resolve("package.json"), "utf-8")).version || version;
} catch {
}
var loginAttempts = /* @__PURE__ */ new Map();
function loginRateLimit(req, res, next) {
  const ip = String(req.headers["x-forwarded-for"] || req.ip || "").split(",")[0].trim() || "unknown";
  const now = Date.now();
  const rec = loginAttempts.get(ip);
  if (!rec || now > rec.reset) loginAttempts.set(ip, { n: 1, reset: now + 6e4 });
  else if (++rec.n > (Number(process.env.AUTH_RATE_LIMIT_PER_MINUTE) || 10)) {
    return res.status(429).json({ error: "Too many login attempts. Wait one minute." });
  }
  next();
}
async function authenticate(req, res, next) {
  const header = String(req.headers.authorization || "");
  const token = header.startsWith("Bearer ") ? header.slice(7).trim() : "";
  if (!token) return next();
  let check;
  try {
    check = verifyJwtToken(token);
  } catch {
    return res.status(503).json({ error: "Online API not configured: JWT_SECRET is missing." });
  }
  if (!check.valid || !check.payload || !isValidUuid(check.payload.userId)) return next();
  try {
    const row = (await withCloud((c) => c.query(
      `SELECT id, name, email, role, local_user_id, shop_id FROM giga_cloud.online_users WHERE id = $1 AND active`,
      [check.payload.userId]
    ))).rows[0];
    if (row) req.onlineUser = row;
    next();
  } catch (err) {
    res.status(503).json({ error: "Cloud database unavailable: cannot verify the session." });
  }
}
var requireAuth = (req, res, next) => req.onlineUser ? next() : res.status(401).json({ error: "Unauthorized: valid Bearer token required." });
var requirePermission = (perm) => (req, res, next) => {
  if (!req.onlineUser) return res.status(401).json({ error: "Unauthorized: valid Bearer token required." });
  if (!hasPermission(req.onlineUser.role, perm)) return res.status(403).json({ error: `Forbidden: role ${req.onlineUser.role} lacks ${perm}.` });
  next();
};
var requireAdmin = (req, res, next) => {
  if (!req.onlineUser) return res.status(401).json({ error: "Unauthorized: valid Bearer token required." });
  if (req.onlineUser.role !== "ADMIN") return res.status(403).json({ error: "Forbidden: Administrator only." });
  next();
};
var CONNECTION_ERRORS = ["ENOTFOUND", "EAI_AGAIN", "ECONNREFUSED", "ECONNRESET", "ETIMEDOUT", "ENETUNREACH", "EHOSTUNREACH"];
function send(res, err, label) {
  if (CONNECTION_ERRORS.includes(err?.code) || /timeout|terminated|Connection/i.test(String(err?.message || ""))) {
    console.error(`[Online] ${label}: cloud database unreachable (${err?.code || err?.message})`);
    return res.status(503).json({ error: "Cloud database unreachable. Try again shortly.", code: "CLOUD_DB_UNREACHABLE" });
  }
  const status = typeof err?.status === "number" ? err.status : 500;
  if (status >= 500) console.error(`[Online] ${label} failed:`, err?.message || err);
  res.status(status).json({ error: status >= 500 && !(err instanceof HttpError) ? "Cloud database error." : err.message });
}
var route = (label, fn) => async (req, res) => {
  try {
    const out = await fn(req, res);
    if (!res.headersSent) res.json(out);
  } catch (err) {
    send(res, err, label);
  }
};
var cashierScope = (u) => u.role === "CASHIER" ? u.local_user_id || "00000000-0000-0000-0000-000000000000" : void 0;
function buildOnlineRouter() {
  const r = express2.Router();
  r.use(authenticate);
  r.get("/health", async (_req, res) => {
    const cfg = getOnlineConfig();
    const base = { status: "online", system: "GIGA CHEMIST POS API", mode: "online", app_mode: "online", version, timestamp: Date.now(), read_only: true };
    if (cfg.error) return res.json({ ...base, database: { provider: "Supabase PostgreSQL", connected: false, configured: false, error: cfg.error } });
    try {
      const info = await withCloud(async (c) => {
        const schema = (await c.query(`SELECT to_regclass('giga_cloud.shops') IS NOT NULL AS cloud, to_regclass('giga_online.sales') IS NOT NULL AS online,
                                              to_regclass('giga_cloud.online_users') IS NOT NULL AS users`)).rows[0];
        const shop = schema.cloud ? (await c.query(`SELECT shop_code, active, last_event_at FROM giga_cloud.shops WHERE shop_id = $1`, [cfg.shopId])).rows[0] : null;
        return { schema, shop };
      });
      res.json({
        ...base,
        auth_configured: Boolean(process.env.JWT_SECRET && process.env.JWT_SECRET.length >= 32),
        database: {
          provider: "Supabase PostgreSQL",
          connected: true,
          cloud_schema: info.schema.cloud,
          online_views: info.schema.online,
          online_accounts_table: info.schema.users,
          shop_registered: Boolean(info.shop),
          shop_code: info.shop?.shop_code || null,
          last_shop_event_at: info.shop?.last_event_at || null
        }
      });
    } catch (err) {
      res.status(503).json({ ...base, status: "degraded", database: { provider: "Supabase PostgreSQL", connected: false, error: "Cloud database unreachable." } });
    }
  });
  r.post("/auth/login", loginRateLimit, async (req, res) => {
    try {
      const identifier = String(req.body?.email || req.body?.username || "").trim().toLowerCase();
      const secret = String(req.body?.password || "").trim();
      if (!identifier || !secret) return res.status(400).json({ error: "Email and password are required." });
      const user = (await withCloud((c) => c.query(
        `SELECT id, name, email, role, password_hash, shop_id FROM giga_cloud.online_users WHERE email = $1 AND active`,
        [identifier]
      ))).rows[0];
      const shopId = getOnlineConfig().shopId;
      if (!user || !verifyCredential(secret, user.password_hash) || user.shop_id && user.shop_id !== shopId) {
        return res.status(401).json({ error: "Invalid email or password." });
      }
      await withCloud((c) => c.query("UPDATE giga_cloud.online_users SET last_login_at = now() WHERE id = $1", [user.id]));
      const token = createJwtToken({ userId: user.id, role: user.role, email: user.email, name: user.name });
      res.json({ success: true, token, user: { id: user.id, name: user.name, email: user.email, role: user.role, active: true }, permissions: ROLE_PERMISSIONS[user.role] });
    } catch (err) {
      send(res, err, "POST /auth/login");
    }
  });
  r.get("/auth/me", requireAuth, (req, res) => {
    const u = req.onlineUser;
    res.json({ user: { id: u.id, name: u.name, email: u.email, role: u.role, active: true }, permissions: ROLE_PERMISSIONS[u.role] });
  });
  r.post("/devices/register", requireAuth, (_req, res) => res.json({ status: "not_tracked_online" }));
  r.get("/settings", route("GET /settings", () => withShop(async (c) => {
    try {
      return await getPharmacySettings(c);
    } catch {
      return toSettings({ pharmacy_name: "GIGA CHEMIST" });
    }
  })));
  r.get("/sync/status", requireAuth, route("GET /sync/status", async () => {
    const cfg = getOnlineConfig();
    const shop = await withCloud((c) => c.query("SELECT last_event_at FROM giga_cloud.shops WHERE shop_id = $1", [cfg.shopId]));
    return { mode: "online", enabled: false, read_only: true, local_database: { connected: true }, cloud_reachable: true, counts: null, last_sync: shop.rows[0]?.last_event_at || null };
  }));
  const stripCost = (req, rows, fields) => req.onlineUser.role === "CASHIER" ? rows.map((x) => Object.fromEntries(Object.entries(x).map(([k, v]) => [k, fields.includes(k) ? 0 : v]))) : rows;
  r.get("/medicines", requirePermission("medicine.view"), route("GET /medicines", async (req) => stripCost(req, await withShop((c) => getAllMedicines(c)), ["purchase_price"])));
  r.get("/categories", requirePermission("medicine.view"), route("GET /categories", () => withShop((c) => getAllCategories(c))));
  r.get("/batches", requirePermission("medicine.view"), route("GET /batches", async (req) => stripCost(req, await withShop((c) => getAllBatches(c)), ["purchase_price"])));
  r.get("/customers", requirePermission("sales.view_own"), route("GET /customers", () => withShop((c) => getAllCustomers(c))));
  r.get("/sales", requirePermission("sales.view_own"), route("GET /sales", async (req) => {
    const q = req.query;
    const result = await withShop((c) => getAllSales({
      page: Number(q.page) || 1,
      limit: Number(q.limit) || 50,
      search: q.search,
      startDate: q.startDate,
      endDate: q.endDate,
      cashierId: cashierScope(req.onlineUser) ?? q.cashierId,
      paymentMethod: q.paymentMethod || void 0,
      customerId: q.customerId || void 0,
      priceMode: q.priceMode || void 0,
      status: q.status || void 0
    }, c));
    if (req.onlineUser.role !== "CASHIER") return result;
    const strip = (s) => ({ ...s, cost_total: 0, gross_profit: 0, items: s.items?.map((i) => ({ ...i, cost_price_snapshot: 0 })) });
    return { ...result, sales: result.sales.map(strip) };
  }));
  r.get("/sales/today-summary", requireAuth, route("GET /sales/today-summary", async (req) => {
    const s = await withShop((c) => getTodaySalesSummary({ cashierId: cashierScope(req.onlineUser) ?? (req.query.cashierId || void 0) }, c));
    if (req.onlineUser.role !== "ADMIN") delete s.grossProfit;
    return s;
  }));
  r.get("/reports/summary", requirePermission("sales.view_own"), route("GET /reports/summary", (req) => withShop(async (c) => {
    const isAdmin = req.onlineUser.role === "ADMIN";
    const range = await resolveRange(req.query.range, req.query.start, req.query.end, c);
    return getSalesReport(range, { cashierId: isAdmin ? req.query.cashierId || null : cashierScope(req.onlineUser), includeCost: isAdmin }, c);
  })));
  r.get("/returns", requirePermission("returns.create"), route("GET /returns", (req) => withShop((c) => {
    const status = typeof req.query.status === "string" && req.query.status ? req.query.status.toUpperCase() : void 0;
    return getAllReturns({ userId: cashierScope(req.onlineUser), status }, c);
  })));
  r.get("/users", requireAdmin, route("GET /users", () => withShop(async (c) => (await c.query("SELECT id, name, email, username, role, active FROM users ORDER BY name")).rows)));
  r.get("/suppliers", requireAdmin, route("GET /suppliers", () => withShop((c) => getAllSuppliers(c))));
  r.get("/purchases", requireAdmin, route("GET /purchases", () => withShop((c) => getAllPurchases(c))));
  r.get("/expenses", requireAdmin, route("GET /expenses", () => withShop((c) => getAllExpenses(c))));
  for (const p of ["/inventory/movements", "/audit", "/admin/health", "/email/settings", "/email/jobs", "/backups/status"]) {
    r.get(p, requireAuth, (_req, res) => res.status(501).json({ error: "Not available online: this information lives on the shop server.", code: "SHOP_SERVER_ONLY" }));
  }
  r.all("*", (req, res, next) => {
    if (req.method === "GET" || req.method === "HEAD") return next();
    res.status(409).json({
      error: "The online app is read-only. Sales, stock, returns, purchases and other changes are made on the shop POS; they reach the cloud through sync.",
      code: "ONLINE_READ_ONLY"
    });
  });
  r.use((req, res) => res.status(404).json({ error: `API route not found: ${req.method} ${req.originalUrl}` }));
  return r;
}
function mountOnlineApi(app2) {
  applyCommonMiddleware(app2);
  app2.use("/api", buildOnlineRouter());
  app2.use("/api", apiErrorHandler);
}

// server/online/vercel-entry.ts
var app = express3();
app.use((req, _res, next) => {
  if (!req.url.startsWith("/api")) req.url = `/api${req.url.startsWith("/") ? "" : "/"}${req.url}`;
  next();
});
mountOnlineApi(app);
var vercel_entry_default = app;
export {
  vercel_entry_default as default
};
